Pages/AvailDesks/Create.cshtml.cs
// Author : Martin Connolly
//
// Description
// Create Available Desks controller

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using HotDesk.Data;
using HotDesk.Models;

namespace HotDesk.Pages.AvailDesks
{
    public class CreateModel : PageModel
    {
        private readonly HotDesk.Data.HotDeskContext _context;

        public CreateModel(HotDesk.Data.HotDeskContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["DeskID"] = new SelectList(_context.Desk, "ID", "ID");
        ViewData["DeskName"] = new SelectList(_context.Desk, "ID", "Name");

        ViewData["ResvDateID"] = new SelectList(_context.ResvDate, "ID", "ID");
        ViewData["ResvDateName"] = new SelectList(_context.ResvDate, "ID", "Name");
        return Page();
        }

        [BindProperty]
        public AvailDesk AvailDesk { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.AvailDesk.Add(AvailDesk);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/AvailDesks/Delete.cshtml.cs
// Author : Martin Connolly
//
// Description
// Delete Available Desks controller

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using HotDesk.Data;
using HotDesk.Models;

namespace HotDesk.Pages.AvailDesks
{
    public class DeleteModel : PageModel
    {
        private readonly HotDesk.Data.HotDeskContext _context;

        public DeleteModel(HotDesk.Data.HotDeskContext context)
        {
            _context = context;
        }

        [BindProperty]
        public AvailDesk AvailDesk { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AvailDesk = await _context.AvailDesk
                .Include(a => a.Desk)
                .Include(a => a.ResvDate).FirstOrDefaultAsync(m => m.ID == id);

            if (AvailDesk == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AvailDesk = await _context.AvailDesk.FindAsync(id);

            if (AvailDesk != null)
            {
                _context.AvailDesk.Remove(AvailDesk);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/AvailDesks/Details.cshtml.cs
// Author : Martin Connolly
//
// Description
// Details Available Desks controller

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using HotDesk.Data;
using HotDesk.Models;

namespace HotDesk.Pages.AvailDesks
{
    public class DetailsModel : PageModel
    {
        private readonly HotDesk.Data.HotDeskContext _context;

        public DetailsModel(HotDesk.Data.HotDeskContext context)
        {
            _context = context;
        }

        public AvailDesk AvailDesk { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AvailDesk = await _context.AvailDesk
                .Include(a => a.Desk)
                .Include(a => a.ResvDate).FirstOrDefaultAsync(m => m.ID == id);

            if (AvailDesk == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/AvailDesks/Edit.cshtml.cs
// Author : Martin Connolly
//
// Description
// Edit Available Desks controller

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HotDesk.Data;
using HotDesk.Models;

namespace HotDesk.Pages.AvailDesks
{
    public class EditModel : PageModel
    {
        private readonly HotDesk.Data.HotDeskContext _context;

        public EditModel(HotDesk.Data.HotDeskContext context)
        {
            _context = context;
        }

        [BindProperty]
        public AvailDesk AvailDesk { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AvailDesk = await _context.AvailDesk
                .Include(a => a.Desk)
                .Include(a => a.ResvDate).FirstOrDefaultAsync(m => m.ID == id);

            if (AvailDesk == null)
            {
                return NotFound();
            }
            ViewData["DeskID"] = new SelectList(_context.Desk, "ID", "ID");
            ViewData["DeskName"] = new SelectList(_context.Desk, "ID", "Name");
            
            ViewData["ResvDateID"] = new SelectList(_context.ResvDate, "ID", "ID");
            ViewData["ResvDateName"] = new SelectList(_context.ResvDate, "ID", "Name");

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(AvailDesk).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AvailDeskExists(AvailDesk.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool AvailDeskExists(int id)
        {
            return _context.AvailDesk.Any(e => e.ID == id);
        }
    }
}

Pages/Desks/Create.cshtml.cs
// Author : Martin Connolly
//
// Description
// Create desks controller

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using HotDesk.Data;
using HotDesk.Models;

namespace HotDesk.Pages.Desks
{
    public class CreateModel : PageModel
    {
        private readonly HotDesk.Data.HotDeskContext _context;

        public CreateModel(HotDesk.Data.HotDeskContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Desk Desk { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Desk.Add(Desk);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Desks/Delete.cshtml.cs
// Author : Martin Connolly
//
// Description
// Delete desks controller

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using HotDesk.Data;
using HotDesk.Models;

namespace HotDesk.Pages.Desks
{
    public class DeleteModel : PageModel
    {
        private readonly HotDesk.Data.HotDeskContext _context;

        public DeleteModel(HotDesk.Data.HotDeskContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Desk Desk { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Desk = await _context.Desk.FirstOrDefaultAsync(m => m.ID == id);

            if (Desk == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Desk = await _context.Desk.FindAsync(id);

            if (Desk != null)
            {
                _context.Desk.Remove(Desk);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Reservations/Details.cshtml.cs
// Author : Martin Connolly
//
// Description
// Details Reservations controller

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using HotDesk.Data;
using HotDesk.Models;

namespace HotDesk.Pages.Reservations
{
    public class DetailsModel : PageModel
    {
        private readonly HotDesk.Data.HotDeskContext _context;

        public DetailsModel(HotDesk.Data.HotDeskContext context)
        {
            _context = context;
        }

        public Reservation Reservation { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Reservation = await _context.Reservation.FirstOrDefaultAsync(m => m.ID == id);

            if (Reservation == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/Reservations/Index.cshtml.cs
// Author : Martin Connolly
//
// Description
// Main reservations grid

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using HotDesk.Data;
using HotDesk.Models;
using Microsoft.AspNetCore.Http;
using System.Globalization;
using System.ComponentModel.DataAnnotations;

namespace HotDesk.Pages.Reservations
{
    public class IndexModel : PageModel
    {
        private readonly HotDesk.Data.HotDeskContext _context;
        public ReservationsViewModel ViewModel { get; set; }
        [BindProperty]
        public DateTime selectedDate { get; set; } = new DateTime(2021, 1, 10);        
        //static DateTime startDate = new DateTime(2021, 1, 10);
        static DateTime startDate = DateTime.Today;

        public IndexModel(HotDesk.Data.HotDeskContext context)
        {
            _context = context;
        }

        public IList<Reservation> Reservation { get; set; }

        public async Task OnGetAsync()
        {
            var viewModel = new ReservationsViewModel();

            //Get list of desks
            List<Desk> deskList = (from d in _context.Desk
                                   orderby d.Name
                                   select d).ToList();

            DateTime checkDate = startDate;
            var deskStatus = new DeskStatus();           
            //int userID = 1;
            int userID = Convert.ToInt32(HttpContext.Session.GetString("ActiveUser"));
            viewModel.SelectedDate = startDate;
            //For each desk check status for next seven days
            foreach (Desk checkDesk in deskList)
            {
                DeskReservation deskReservation = new DeskReservation();
                deskReservation.DeskID = checkDesk.ID;
                deskReservation.DeskName = checkDesk.Name;
                for (int i = 0; i < 7; i++)
                {
                    checkDate = startDate.AddDays(i);
                    // List of date ranges containing check date
                    List<ResvDate> containingRanges = (from r in _context.ResvDate
                                                       where r.FromDate <= checkDate && r.ToDate >= checkDate
                                                       select r).ToList();
                    if (containingRanges.Count == 0)
                    {
                        deskStatus = DeskStatus.UnAvailable;
                    }
                    else
                    {
                        //Is there a reservation for that desk / date combo?

                        List<Reservation> deskReservations = (from r in _context.Reservation
                                                              where r.DeskID == checkDesk.ID && r.ResvDate == checkDate
                                                              select r).ToList();
                        if (deskReservations.Count > 0 && deskReservations.ElementAt(0).UserID.Equals(userID))
                        {
                            deskStatus = DeskStatus.BookedByMe;
                        }
                        if (deskReservations.Count > 0 && !deskReservations.ElementAt(0).UserID.Equals(userID))
                        {
                            deskStatus = DeskStatus.BookedByOther;
                        }
                        if (deskReservations.Count == 0)
                        {
                            deskStatus = DeskStatus.Available;
                        }
                    }
                    DeskDateStatus deskDateStatus = new DeskDateStatus();
                    deskDateStatus.ReservationDate = checkDate;
                    deskDateStatus.ReservationStatus = deskStatus;
                    deskReservation.AddStatus(deskDateStatus);
                    //deskReservation.DeskDateStatuses.Add(deskDateStatus);


                }
                viewModel.AddDeskReservation(deskReservation);
            }
            this.ViewModel = viewModel;
        }
        public async Task<IActionResult> OnPost()
        {
            startDate = selectedDate;
            return RedirectToAction("OnGet");
        }
        public async Task<IActionResult> OnPostDateChange()
        {
            startDate = selectedDate;
            return RedirectToAction("OnGet");
        }

        public async Task<IActionResult> ChangeStatus(int deskID, DateTime resDate)
        {
            
            return RedirectToAction("OnGet");
        }

        public async Task<IActionResult> OnGetChangeReservationStatus(String resDate,int id, DeskStatus status)
        {
            int deskId = id;
            int userID = Convert.ToInt32(HttpContext.Session.GetString("ActiveUser"));

            DateTime resvDate = DateTime.ParseExact(resDate, "dd-MM-yyyy", System.Globalization.CultureInfo.InvariantCulture);
            if (status==DeskStatus.Available)
            {
                var newReservation = new Reservation();
                newReservation.DeskID = id;
                newReservation.ResvDate = resvDate;
                newReservation.UserID = userID;
                _context.Reservation.Add(newReservation);
                await _context.SaveChangesAsync();
            }
            if (status == DeskStatus.BookedByMe)
            {
                List<Reservation> delReservation = (from r in _context.Reservation
                                    where r.ResvDate == resvDate && r.DeskID == id && r.UserID==userID
                                    select r).ToList();
                _context.Reservation.Remove(delReservation[0]);
                await _context.SaveChangesAsync();
            }


            return RedirectToAction("OnGet");
        }

    }
    public enum DeskStatus
    {
        [Display(Name="Available")]
        Available = 0,
        [Display(Name = "Unavailable")]
        UnAvailable = 1,
        [Display(Name = "Mine")]
        BookedByMe = 2,
        [Display(Name = "Other")]
        BookedByOther = 3
    }
    public class DeskReservation
    {
        public int DeskID { get; set; }
        public string DeskName { get; set; }
        private List<DeskDateStatus> deskDateStatuses = new List<DeskDateStatus>();
        public List<DeskDateStatus> DeskDateStatuses {
            //get => this.deskDateStatuses == null ? new List<DeskDateStatus>() : this.deskDateStatuses; // Ternary operator
            get => this.deskDateStatuses;
             
        }
        public void AddStatus(DeskDateStatus deskDatestatus)
        {
            this.DeskDateStatuses.Add(deskDatestatus);
        }
    }

    public class DeskDateStatus
    {
        public DateTime ReservationDate { get; set; }
        public DeskStatus ReservationStatus { get; set; }
    }

    public class ReservationsViewModel 
    {
        public DateTime SelectedDate { get; set; }
        private List<DeskReservation> deskReservations = new List<DeskReservation>();
        public List<DeskReservation> DeskReservations { get => this.deskReservations; }
        public void AddDeskReservation(DeskReservation deskReservation)
        {
            this.DeskReservations.Add(deskReservation);
        }
    }
}

Pages/Reservations/Create.cshtml
@page
@model HotDesk.Pages.Reservations.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Reservation.UserID" class="control-label"></label>
                <input asp-for="Reservation.UserID" class="form-control" />
                <span asp-validation-for="Reservation.UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reservation.DeskID" class="control-label"></label>
                <input asp-for="Reservation.DeskID" class="form-control" />
                <span asp-validation-for="Reservation.DeskID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reservation.ResvDate" class="control-label"></label>
                <input asp-for="Reservation.ResvDate" class="form-control" />
                <span asp-validation-for="Reservation.ResvDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Reservations/Delete.cshtml
@page
@model HotDesk.Pages.Reservations.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reservation.UserID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Reservation.UserID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reservation.DeskID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Reservation.DeskID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reservation.ResvDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Reservation.ResvDate)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Reservation.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Reservations/Details.cshtml
@page
@model HotDesk.Pages.Reservations.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reservation.UserID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Reservation.UserID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reservation.DeskID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Reservation.DeskID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reservation.ResvDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Reservation.ResvDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Reservation.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Reservations/Edit.cshtml
@page
@model HotDesk.Pages.Reservations.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Reservation.ID" />
            <div class="form-group">
                <label asp-for="Reservation.UserID" class="control-label"></label>
                <input asp-for="Reservation.UserID" class="form-control" />
                <span asp-validation-for="Reservation.UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reservation.DeskID" class="control-label"></label>
                <input asp-for="Reservation.DeskID" class="form-control" />
                <span asp-validation-for="Reservation.DeskID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reservation.ResvDate" class="control-label"></label>
                <input asp-for="Reservation.ResvDate" class="form-control" />
                <span asp-validation-for="Reservation.ResvDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Reservations/Index.cshtml
@page
@model IndexModel

@{
    ViewData["Title"] = "Index";
}
<style>
    td
    {
        border: 1px solid black;
    }
</style>
<h1>Reservations</h1>
<br />
<form method="post" asp-page-handler="DateChange">
    <div>
        <input asp-for="selectedDate" onchange="this.form.submit();" type="date" id="startDate" value="@Model.ViewModel.SelectedDate.ToString("yyyy-MM-dd")">
    </div>
</form>
<br />
<br />

<form method="post" asp-page-handler="DateChange">
    <table id="DeskReservationsContainer">
        <tr id="DaysHeaderContainer">
            <th class="deskName"></th>
            @for (int i = 0; i < 7; i++)
            {
                <th class="day">@Model.ViewModel.SelectedDate.AddDays(i).ToString("ddd dd/MM")</th>
            }

        </tr>
        @foreach (var desk in Model.ViewModel.DeskReservations)
        {
            <tr id="DeskRowsContainer">
                <td class="deskName">@desk.DeskName</td>
                @foreach (var day in desk.DeskDateStatuses)
                {
                    <td class="day @day.ReservationStatus">
                        
                        <div>                            
                            <a asp-page-handler="ChangeReservationStatus" asp-route-resDate= "@day.ReservationDate.ToString("dd-MM-yyyy")" asp-route-id="@desk.DeskID" asp-route-status="@day.ReservationStatus">@day.ReservationStatus</a>
                        </div>
                    </td>
                }

            </tr>

        }
    </table>
</form>